#!/bin/zsh
#
# MIT License
#
# Copyright (c) 2020 Anthony Muller
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#------------------------------------------------------------------------------#
#  Check if VPN is connected by looking for the utun interface and IP address.
#
#  In my tests, the utun5 interface will only exist when connected to VPN. In
#  the event it does exist, it should not have an IP address assigned to it
#  until you are connected to the VPN provider.
#------------------------------------------------------------------------------#

# Force using the Apple ifconfig to avoid checking for GNU version.
OUTPUT=""

for i in $(ifconfig | awk '$1 ~ "^(utun|ipsec)[0-9]+:" {gsub(/:/,"",$1); print $1}')
do
    OUT=$(ifconfig $i | grep "inet ")
    if [[ $OUT != "" ]]; then
        OUTPUT=$OUT
    fi
done

if [[ $OUTPUT == "" ]]; then
    echo -e "\033[31mVPN\033[m"
else
    echo -e "\033[30;42mVPN\033[m"
fi
