#!/bin/zsh
#
# MIT License
#
# Copyright (c) 2020 Anthony Muller
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#------------------------------------------------------------------------------#
#  Check if VPN is connected by looking for the utun interface and IP address.
#
#  In my tests, the utun5 interface will only exist when connected to VPN. In
#  the event it does exist, it should not have an IP address assigned to it
#  until you are connected to the VPN provider.
#------------------------------------------------------------------------------#

# Force using the Apple ifconfig to avoid checking for GNU version.
OUTPUT=$(/sbin/ifconfig utun5 2&>/dev/null | grep "inet" | grep " 10\.")

# If it finds a 10. IP address, then return code will be 0, otherwise 1.
RESULT=$?
if [[ $RESULT -ne 0 ]]; then
    echo -e "\033[31mVPN\033[m"
else
    echo -e "\033[30;42mVPN\033[m"
fi
